Resolves a NoMethodError when running `rpush init` on Rails 7
Running `rpush init` results in the following error, beginning with
Rails version `v7.0.0.rc1`.

` undefined method `[]' for #<ActiveRecord::DatabaseConfigurations:0x00007f82dcdcc010> (NoMethodError)`

1. Create a new Rails app, using Rails version v7.0.0.rc1 or higher.
2. Add rpush to the Gemfile, and run `bundle install`.
3. Run `bundle exec rpush init`.

This exception could also occur on apps running Rails 7 that have been
running older versions of rpush older than 2.0.0 (when the app is
updated to a new version of rpush, users run `rpush init`).

The changes introduced on f88febec266087be021d3cd6fb045f328519d2e7
trigger the exception:

https://github.com/rpush/rpush/runs/4545600006?check_suite_focus=true#step:6:13

```
/home/runner/work/rpush/rpush/lib/generators/templates/rpush_2_0_0_updates.rb:61:in `adapter_name': undefined method `[]' for #<ActiveRecord::DatabaseConfigurations:0x000055cead615a40 @configurations=[#<ActiveRecord::DatabaseConfigurations::HashConfig:0x000055cead6156f8 @env_name="test", @name="primary", @configuration_hash={:adapter=>"postgresql", :database=>"rpush_test", :host=>"localhost", :username=>"postgres", :***"postgres"}>]> (NoMethodError)
```

`ActiveRecord::Base.configurations.to_h` was removed in Rails 7
in favor of `ActiveRecord::Base.configurations.configs_for`.

https://github.com/rails/rails/commit/190f006e78fcf2d5f4e4565f2d25b12545f12dde
https://edgeguides.rubyonrails.org/7_0_release_notes.html#active-job-removals
https://www.bigbinary.com/blog/rails-6-changed-activerecord-base-configurations-result-to-an-object